# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 30158336c3e4e15d2ee4e0d44290d1b00556ff66

{
  "title": "Ноут IKEA",
  "description": "Не очень срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 30158336c3e4e15d2ee4e0d44290d1b00556ff66

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2021-07-29
Content-Type: application/json
